#pragma once

#define SAMWISE_POWER_MONITOR_I2C (I2C_INSTANCE(0))
#define SAMWISE_POWER_MONITOR_SDA_PIN (36)
#define SAMWISE_POWER_MONITOR_SCL_PIN (37)
#define SAMWISE_WATCHDOG_FEED_PIN (42)

#define ADCS_MOTOR_SDO 32
#define ADCS_MOTOR_SDI 35
#define ADCS_MOTOR_SCLK 38

#define MOTOR_0_FAULT_PIN 10
#define MOTOR_0_SLEEP_PIN 4
#define MOTOR_0_DRVOFF_PIN 6
#define MOTOR_0_SCS_PIN 1
#define MOTOR_0_BRAKE_PIN 2
#define MOTOR_0_PWM_PIN 3
#define MOTOR_0_FGOUT_PIN 0

#define MOTOR_1_FAULT_PIN 12
#define MOTOR_1_SLEEP_PIN 11
#define MOTOR_1_DRVOFF_PIN 13
#define MOTOR_1_SCS_PIN 5
#define MOTOR_1_BRAKE_PIN 9
#define MOTOR_1_PWM_PIN 8
#define MOTOR_1_FGOUT_PIN 7

#define MOTOR_2_FAULT_PIN 19
#define MOTOR_2_SLEEP_PIN 18
#define MOTOR_2_DRVOFF_PIN 20
#define MOTOR_2_SCS_PIN 17
#define MOTOR_2_BRAKE_PIN 16
#define MOTOR_2_PWM_PIN 15
#define MOTOR_2_FGOUT_PIN 14

#define MOTOR_3_FAULT_PIN 26
#define MOTOR_3_SLEEP_PIN 25
#define MOTOR_3_DRVOFF_PIN 27
#define MOTOR_3_SCS_PIN 21
#define MOTOR_3_BRAKE_PIN 23
#define MOTOR_3_PWM_PIN 22
#define MOTOR_3_FGOUT_PIN 24

